[algo.FromConfig]
type = "tabular_q_learning"

min_e = 0.1
decay_rate_e = 0.995
learning_rate = 0.2
reward_discount_factor = 0.99
max_steps_per_epoch = 250


[env]
width = 10
height = 10

start_x = 0
start_y = 0

goal_x = 9
goal_y = 9

maze_difficulty = 0.5
reward_type = "Flat"


[training]
epochs = 500


[action.SolutionVisualization]
saving_path = "./assets/"
show_info_in_plot = true
create_video = false
