[algo.Load]
path = "./assets/model.json"


[env]
width = 15
height = 15

start_x = 0
start_y = 0

goal_x = 14
goal_y = 14

reward_type = "Flat"


[training]
epochs = 0


[action.SolutionVisualization]
saving_path = "./assets/"
show_info_in_plot = false
create_video = true
