[algo.FromConfig.DeepQLearning]
min_e = 0.01
decay_rate_e = 0.995
learning_rate = 1e-2
reward_discount_factor = 0.99

batch_size = 256
n_rollouts = 2000
replay_memory_capacity = 20000
n_epochs = 8
n_epochs_to_update_target = 16
q_network_layers = [3, 64, 3]
net_path = "./assets/"


[env.Plane]
width = 10.0
height = 10.0
n_rays = 0
length_ray = 2.0
ray_span = 1.57 # In radians
reward_type = "Additive"

agent_pos = { Fixed = { pos = [
    [0.0, 0.0],
] } }
goal_pos = { Fixed = { pos = [
    [9.0, 9.0],
] } }
obstacles_config = { Fixed = { pos = [
    # [4.0, 4.0],
] } }


[training]
epochs = 2000
max_steps_per_epoch = 1000
regenerate_every = 1000
update_graphics_every = 250
seed = 0


[action.SolutionVisualization]
saving_path = "./assets/"
create_video = true
plots = [
    [
        "DQL algorithm on plane",
        [
            ["Reward", 1.0],
            ["Loss", 0.4],
        ],
        true
    ],
    [
        "DQL algorithm on plane",
        [
            ["Epsilon", 0.2]
        ],
        false
    ]
]
