[algo.Load]
path = "./assets/model.json"


[env.Grid]
width = 15
height = 15

start_x = 0
start_y = 0

goal_x = 14
goal_y = 14

reward_type = "Flat"


[training]
epochs = 0
max_steps_per_epoch = 250
update_graphics_every = 0
regenerate_every = 0
seed = 1


[action.SolutionVisualization]
saving_path = "./assets/"
create_video = true
plots = []