[algo.FromConfig.PPO]
actor_layers = [4, 128, 3]
critic_layers = [4, 128, 1]
actor_lr = 5e-4
critic_lr = 5e-4
lmbda = 0.95
epochs = 4
batch_size = 8
mini_batch_size = 16
epsilon = 0.2
gamma = 0.99
current_entropy_weight = 0.0
min_entropy = 0.0
decay_rate_entropy = 0.99
net_path = "./assets/"

# [algo.Load]
# path = "assets/model.json"



[env.Plane]
width = 10.0
height = 10.0
n_rays = 0
length_ray = 2.0
ray_span = 1.57 # In radians
reward_type = "Additive"

agent_pos = { Fixed = { pos = [
    [0.0, 0.0],
] } }
goal_pos = { Fixed = { pos = [
    [9.0, 9.0],
] } }
obstacles_config = { Fixed = { pos = [] } }


[training]
epochs = 1000
max_steps_per_epoch = 1000
regenerate_every = 1000
update_graphics_every = 50


[action.SolutionVisualization]
saving_path = "./assets/"
create_video = true
plots = [
    [
        "PPO algorithm on Continuous Environment",
        [
            ["Reward", 1.0],
            ["Entropy", 1.0],
        ],
        true
    ],
    [
        "PPO algorithm on plane",
        [
            ["Reward", 1.0],
        ],
        true
    ],
    [
        "PPO algorithm on Continuous Environment",
        [
            ["Actor Loss", 0.999],
            ["Critic Loss", 1.0],
        ],
        true
    ],
]