[algo.FromConfig.TabularQLearning]
min_e = 1e-3
decay_rate_e = 0.99
learning_rate = 0.2
reward_discount_factor = 0.99


[env.Grid]
width = 10
height = 10

start_x = 0
start_y = 0

goal_x = 9
goal_y = 9

reward_type = "Flat"


[training]
epochs = 1000
max_steps_per_epoch = 20
update_graphics_every = 0
regenerate_every = 0
seed = 0


[action.CompareEnvironmentRewardType]
n_iterations = 25
saving_path = "./assets/"
