[algo.FromConfig.DeepQLearning]
min_e = 0.05
decay_rate_e = 0.995
learning_rate = 1e-3
reward_discount_factor = 0.99

batch_size = 256
n_rollouts = 1000
n_epochs = 8
n_epochs_to_update_target = 8
replay_memory_capacity = 20000
q_network_layers = [2, 64, 3]

[env.Plane]
width = 10.0
height = 10.0
start_x = 0.0
start_y = 0.0
goal_x = 5.0
goal_y = 5.0
n_rays = 0
length_ray = 2.0
ray_span = 1.57 # In radians
reward_type = "Gradient"

obstacles = [
    # [3.0, 5.0]
]


[training]
epochs = 750
max_steps_per_epoch = 1000


[action.SolutionVisualization]
saving_path = "./assets/"
create_video = true
plots = [
    [
        "DQL algorithm on plane",
        [
            ["Reward", 1.0],
            ["Loss", 0.4],
        ],
        true
    ],
    [
        "DQL algorithm on plane",
        [
            ["Epsilon", 0.2]
        ],
        false
    ]
]
