[algo.FromConfig.Evolutionary]
nn_layers = [8, 64, 3]
population_size = 100
elite_count = 2
mutation_rate = 0.2
mutation_strength = 0.5
mutation_strength_decay = 0.99
min_mutation_strength = 0.1


[env.Plane]
width = 10.0
height = 10.0
start_x = 0.0
start_y = 0.0
goal_x = 9.0
goal_y = 9.0
n_rays = 5
length_ray = 2.0
ray_span = 1.57 # In radians
reward_type = "Flat"

obstacles = [
    [3.0, 3.0]
]


[training]
epochs = 50
max_steps_per_epoch = 1000


[action.SolutionVisualization]
saving_path = "./assets/"
show_info_in_plot = true
create_video = true
